### PR TITLE
Merge opsmx/oes-gate repo into forked spinnaker gate repo

### PR DESCRIPTION
**Pull request by abhinaybyrisetty**
List of commits merged:

142f6245 Merge remote-tracking branch 'opsmx/master' into merge-oes
1929023d Merge pull request #188 from OpsMx/OP-5567-AP
2fa6086d OP-5567 : Added new request param for AP test-verification endpoint
670f49f3 Merge pull request #187 from OpsMx/OP-5567
1ba7be10 OP-5567 : Added new request param for AP test-verification endpoint
a0137bdd Merge pull request #186 from OpsMx/ap-testverification
0c3481af Added verificationType request param
234b8823 Merge pull request #185 from Pranav-b-7/echo-bugs
c313f90f One POST endpoint entry added
bcd3604c Merge pull request #183 from OpsMx/OP-5210
5d6e91d8 Updated the OAUTH2 configuration
9577d896 Added the OAUTH2 configuration
6da999c8 Merge remote-tracking branch 'opsmx/master' into merge-oes
1018025a Merge pull request #182 from Pranav-b-7/OP-5502
1dd50e91 shell script modified to write to log file
d7424625 Merge oes-gate into spinnaker gate
39a44903 Updated the ldap false
b8e9d18d Added the oauth2 configuration
88160bf8 Merge pull request #181 from Pranav-b-7/support-echo-events
ad1254e5 Merge branch 'master' into support-echo-events
be705986 Merge pull request #180 from OpsMx/OP-5517
300456a6 support-echo-events
91e09ba6 OP-5517 : Added RequestParam filed
466f5cfc Added the ldap configuration which will bring the Roles
500b1c99 Added the ldap configuration which will bring the Roles
a6a3359c (origin/master, origin/HEAD, master) Rename Docker-opsmx-ubuntu-gate.txt to Dockerfile-opsmx-ubuntu
80d3cd0c Add files via upload
cf1c49df Rename Docker-opsmx-ubi8-gate.txt to Dockerfile
5dfca09b Add files via upload
de08176b Merge pull request #177 from Pranav-b-7/registerCanary
9e7abfd9 Location header changes and JSON mapping to support multiple JSON format for register canary API added
681672de register canary v3 endpoint bypassed
d84eee30 Merge pull request #174 from Pranav-b-7/master
dba8608d testcaseid param added
bb690470 Merge pull request #170 from Pranav-b-7/canary-endpoint-changes
7cd4f8f7 removed unused import
4236dc56 Query param changes added
95bcb9f1 Merge pull request #161 from sudhakaropsmx/master
a7c7e086 Added the new method for Spinnaker Cloud Providers
9fd9ce6d Merge pull request #148 from sudhakaropsmx/master
cd610b66 Added the new method for Spinnaker x509  configuration along with file upload
3820b651 Merge pull request #147 from Pranav-b-7/pagination-parameters
a45ecd86 Pagination parameters added
740d7903 Merge pull request #146 from Pranav-b-7/master
b73b6e3e search and order param added
7d199f4d Merge pull request #145 from Pranav-b-7/master
c1192e12 Pagination parameters added
f77fbf61 Merge pull request #131 from Pranav-b-7/location-header-for-autopilot
4a351543 auth by pass for /autopilot/api/v2/autopilot/canaries/{id} API
bd6e5fee added getters and setter
fd8fbee9 bug fix
2e537c48 Merge pull request #130 from Pranav-b-7/location-header-for-autopilot
fa701778 Register canary API handled seperately to pass the location header
0c96dcbf Merge pull request #129 from Pranav-b-7/bypass-v2-register-canary
4223fa8e bypass-v2-register-canary
19b9c403 Merge pull request #128 from Pranav-b-7/allow-location-header
569c23d8 Trigger api handled seperately
e85661b4 fixes added
c97be6b0 fixes added
7827c543 fixes added
ae1f3243 fixes added
b8c7c2cb fixes added
e3a72db9 fixes added
97acd65f fixes added
0781c22a fix
707ad3e8 log
27c538be fix
c1d5eeca fix
8a5def4e Response class created
3d4f8225 made some changes
7dc450ca empty body added in response
860217f6 Merge pull request #113 from Pranav-b-7/allow-location-header
b6c44163 HTTP status header added
ef155a55 Merge pull request #112 from Pranav-b-7/allow-location-header
f7d199ac import statement added
6df83517 Merge pull request #111 from Pranav-b-7/allow-location-header
979a16c6 Merge branch 'master' into allow-location-header
6d8515bd trigger API handled seperately to pass location headers
5fcbc8ba Merge pull request #110 from Pranav-b-7/OP-4173
004b4a9e UI redirects to localhost:9000 after login - issue resolved
2a0b147d config url
9e1701a2 logger added
87465648 External IP added in config
8969744c made some changes
54fe44d0 config added to redirect to UI
5c4dd6c3 Bug - UI redirects to localhost:9000 after login
aca09a4d Bug - UI redirects to localhost:9000 after login
6c4a1674 Merge pull request #101 from Pranav-b-7/OP-4927
9eff724c Support added for get policy violation API in SAPOR
f6ba3bb1 Merge pull request #100 from sudhakaropsmx/master
9d7a8dfa Added the manifest file download request message
925cbb43 added new method for upload multipart files
c13b1bf5 Merge pull request #94 from Pranav-b-7/OP-4818
bcf511be v1 trigger URL retained
bdbea325 Authentication by pass for visibility trigger API and status API
4bab6b17 Merge pull request #93 from Pranav-b-7/OP-3097
09108315 some changes made to add the response headers
5ff85d2d Merge pull request #88 from Pranav-b-7/OP-3097
20daca15 Removed few spaces
3665ba68 Removed few unused imports
3fc6e78e try with finally block added
555d72e6 bug fixes
0d9ab71f Added some changes
1c54df74 Added some changes
763d6634 Seperate API added to invoke download debug data API
2a297b32 loggers added
4e2b0041 loggers added
341a3f22 Autopilot API modified to return byte data
45530fc3 Merge pull request #79 from OpsMx/delete_tool_connectors_configured_approvalgate
65e9ec5a worked on delete tool connector approval gate
0bf2d0bc Merge pull request #78 from OpsMx/datasource_delete_datasource_fix
8b9dc009 worked on delete platform datasource type
8a86fedd Merge pull request #77 from OpsMx/OP-4616
2a3f83df Added query params in visibility service
3ff1bb3c Added query params
accfccae Merge pull request #74 from OpsMx/yugaa22-patch-1
6c790974 Update README.md
89436baf Merge pull request #67 from Pranav-b-7/master
959bc2b3 session timeout increased to 2 hrs
3ccd1b56 Session time check
7cac85fb Merge pull request #63 from OpsMx/OP-4195-Login-Screen-Changes
f7333957 Modified login screen
05513710 Merge pull request #62 from sudhakaropsmx/master
82a26e0f Updated the Gate code for Dynamic accounts for handle Multipart request OP-4074: Dynamic Accounts configuration in SAPOR
ff98bf65 Merge pull request #61 from OpsMx/OP-3853-Login-Ui-Design-Change
b4db2989 Modified login screen design. Added resource folders CSS, images etc.
7739b3f8 Merge pull request #60 from OpsMx/OP-3853-Customize-Gate-Login-Form
5de0de73 Removed dummy templates
60748795 Removed dummy templates
b80f8f09 Code to customize login form
084e489f Merge pull request #58 from sudhakaropsmx/master
65836f49 Updated Request URL for add or update dynamic accounts
0c432fe1 Merge pull request #56 from OpsMx/VisibiityAutopilotEndpoints
077e93fa Added query param to the autopilot endpoint
1696729b Merge pull request #55 from Pranav-b-7/OP-3829
0462f052 Bypass the external CD tool request and create entries for all new autopilot requests as part of visibility
60298af8 Merge pull request #54 from sudhakaropsmx/master
13743385 Added the DELETE,UPDATE Method allow more resource
1f270937 Merge pull request #53 from sudhakaropsmx/master
953b7ed0 Added the DELETE,UPDATE Method allow more resource
a4e40556 Merge pull request #52 from Pranav-b-7/master
a407bf6c Added referer param
91023d93 Added referer param
b0753d9f Update AuthConfig.groovy
d701fc20 By passing authentication for autopilot/canaries API (#49)
0e0c9255 Merge pull request #48 from Pranav-b-7/OP-3679
f9a663e4 Added some more path variables for dashboard and visibility service
7a0fe88b Merge pull request #47 from Pranav-b-7/OP-3679
d4affb95 Visibility service configurations added
8973440a Merge pull request #44 from OpsMx/RemovedTimeParam
19814ca8 Removed time param in GET api
cd1b11a2 Merge pull request #43 from OpsMx/TimeCorrelationParam
f5174875 Added time query param in services
10fcbaa2 Added time query param
f0985451 Added time parameter to the existing API
5aea8d9b Added time correlation API's (#28)
bbaf2c31 (origin/v3.0, master) Merge pull request #22 from OpsMx/Autopilot_PUT_Config
43188adf Autopiot apis for put methods
8443229e Merge pull request #21 from OpsMx/Platform_Param
e84675fd Updated new params
54326441 Merge pull request #20 from OpsMx/NewParamsForAutopilot
fe43b564 Added new params
842d7bb8 Updating missing format (#19)
d8ce49ad OES and platform endpoints (#9)
3aa5eb59 Merge pull request #8 from OpsMx/newapi_auto
c29807c3 added api
25bf179e Merge pull request #7 from OpsMx/autopilot_newparams
636046e9 Updated new params of autopilot
57a0dc15 Merge pull request #6 from OpsMx/api_bugs
65447b60 fixed api bugs in autopilot
33ecb6ed Merge pull request #5 from OpsMx/file_based_login
46e20a9e File based login added
03d27290 Merge pull request #4 from OpsMx/dashboard_service_integration
20e14b2c Added dashboard service and some more endpoints
9420c7e1 (tag: Release_2_11) Merge pull request #3 from OpsMx/gateapicall
d60d0a0b Updated api response
c2acf6a3 Api for group call
650f6dae Merge pull request #2 from OpsMx/integrateplatform
92be47bd Platform service endpoints added
eead6c07 Merge pull request #1 from OpsMx/gatejwt
1ec76bfb Modified configs and controllers
d4d70688 added spinnaker schedulers as configurable
ac151160 Gate with autopilot changes draft
51576ac7 Added oes services in the gate.
99c2d107 Added oes services in the gate.

### CODE REVIEW

**Review by Pranav-b-7 — APPROVED** [review]
Looks good for me

**Review by Pranav-b-7 — CHANGES_REQUESTED** [review]
I think few changes are replaced. I dont see some latest changes here. Please recheck

**Comment by abhinaybyrisetty** [comment]
> I think few changes are replaced. I dont see some latest changes here. Please recheck

I just fetched the latest changes, please check

**Review by harshaOpsMx — COMMENTED** [review]
Looks good

**Review by harshaOpsMx — APPROVED** [review]
Looks good

**Pull request merged**
