### PR TITLE
OP-16992 : Added parameter for PipelineAndPolicy summarycount

### PR DESCRIPTION
**Pull request by sudhakaropsmx**
https://devopsmx.atlassian.net/browse/OP-17066

### CODE REVIEW

**Comment by opsmxuser** [comment]
This PR  triggered this build in this execution, please wait for it  and child pipelines to succeed before merging:  https://isd.prod.opsmx.net/deck/#/applications/gcp-gitprtrigger/executions/details/01G9PADJGF3NVE7EYXH0J2JCAW

**Comment by opsmxuser** [comment]
This PR  triggered this build in this execution, please merge to master only if this succeeds:  https://isd.prod.opsmx.net/deck/#/applications/gcp-gitprtrigger/executions/details/01G9PADTJM7PCRV5ES7WECGYJ5

**Comment by opsmxuser** [comment]
FAILURE:  RunTests RESULT: <b>Tests run: 217, Failures: 8, Errors: 0, Skipped: 17, Time elapsed: 276.286 sec <<< FAILURE!</b> Reviewers , do not approve,  this PR caused the failures in  https://jenkins.opsmx.net:8181/jenkins/job/Dev-run-tests-on-gitpr-parallel/ws/emailable-report-401.html

**Comment by opsmxuser** [comment]
More tests failed in this pipeline execution than in the preceding one, check logs here https://kibana.opsmx.net/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-08-05T06:23:45.000Z',to:'2022-08-05T06:28:48.000Z'))&_a=(columns:!(kubernetes.namespace_name,kubernetes.pod_name,message,kubernetes.container_name),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'05ac0db0-9319-11ec-9449-f5dd1683b5be',key:kubernetes.namespace_name,negate:!f,params:(query:gitpr),type:phrase),query:(match:(kubernetes.namespace_name:(query:gitpr,type:phrase))))),index:'05ac0db0-9319-11ec-9449-f5dd1683b5be',interval:auto,query:(language:kuery,query:''),sort:!(!('@timestamp',desc)))

**Review by rahul-chekuri — APPROVED** [review]

**Pull request merged**
