### PR TITLE
feature/OP-17225:v4.1:added sort-search logic for listing records

### PR DESCRIPTION
**Pull request by SheetalAtre**
We prefer small, well tested pull requests.

Please refer to [Contributing to Spinnaker](https://spinnaker.io/community/contributing/).

When filling out a pull request, please consider the following:

* Follow the commit message conventions [found here](https://spinnaker.io/community/contributing/submitting/).
* Provide a descriptive summary for your changes.
* If it fixes a bug or resolves a feature request, be sure to link to that issue.
* Add inline code comments to changes that might not be obvious.
* Squash your commits as you keep adding changes.
* Add a comment to @spinnaker/reviewers for review if your issue has been outstanding for more than 3 days.

Note that we are unlikely to accept pull requests that add features without prior discussion. The best way to propose a feature is to open an issue first and discuss your ideas there before implementing them.

https://devopsmx.atlassian.net/browse/OP-17225

### CODE REVIEW

**Comment by opsmxuser** [comment]
This PR  triggered this build in this execution, please wait for it  and child pipelines to succeed before merging:  https://isd.prod.opsmx.net/deck/#/applications/gcp-gitprtrigger/executions/details/01GCVW05AQT7T9YFMAY82NGE3Q

**Comment by opsmxuser** [comment]
This PR  triggered this build in this execution, please merge to master only if this succeeds:  https://isd.prod.opsmx.net/deck/#/applications/gcp-gitprtrigger/executions/details/01GCVW0QG5HPT8ZTFR69GAXEED

**Comment by opsmxuser** [comment]
SUCCESSFUL RunTests RESULT: <b>Tests run: 237, Failures: 18, Errors: 0, Skipped: 37, Time elapsed: 165.359 sec <<< FAILURE!</b> Reviewers ,  this PR did not cause the failures in  https://jenkins.opsmx.net:8181/jenkins/job/Dev-run-tests-on-gitpr-parallel/ws/emailable-report-465.html

**Comment by opsmxuser** [comment]
This PR  triggered this build in this execution, please wait for it  and child pipelines to succeed before merging:  https://isd.prod.opsmx.net/deck/#/applications/gcp-gitprtrigger/executions/details/01GD0GTQTK9RWCT213W8Q3EX8T

**Comment by opsmxuser** [comment]
This PR  triggered this build in this execution, please merge to master only if this succeeds:  https://isd.prod.opsmx.net/deck/#/applications/gcp-gitprtrigger/executions/details/01GD0GV9VD29KAAWC4JCBY3HKK

**Review by rsh09 — APPROVED** [review]

**Pull request merged**
