### PR TITLE
OP-11995: Added favicon.ico to the login page.

### PR DESCRIPTION
**Pull request by rahul-chekuri**
https://devopsmx.atlassian.net/browse/OP-11995

'/error' page redirect can happen in various cases. As per recent logs, this is due to a favicon resource not found issue. Please refer to the logs below.

> 2022-03-21 03:47:38.105 DEBUG 7 --- [nio-8084-exec-1] o.s.s.w.a.i.FilterSecurityInterceptor    : Secure object: FilterInvocation: URL: /favicon.ico; Attributes: [permitAll]
2022-03-21 03:47:38.105 DEBUG 7 --- [nio-8084-exec-1] o.s.s.w.a.i.FilterSecurityInterceptor    : Previously Authenticated: org.springframework.security.authentication.AnonymousAuthenticationToken@5b489844: Principal: anonymousUser; Credentials: [PROTECTED]; Authenticated: true; Details: org.springframework.security.web.authentication.WebAuthenticationDetails@ffffc434: RemoteIpAddress: 10.128.0.71; SessionId: null; Granted Authorities: ROLE_ANONYMOUS
2022-03-21 03:47:38.105 DEBUG 7 --- [nio-8084-exec-1] o.s.s.access.vote.AffirmativeBased       : Voter: org.springframework.security.web.access.expression.WebExpressionVoter@52fe2edd, returned: 1
2022-03-21 03:47:38.105 DEBUG 7 --- [nio-8084-exec-1] o.s.s.w.a.i.FilterSecurityInterceptor    : Authorization successful
2022-03-21 03:47:38.105 DEBUG 7 --- [nio-8084-exec-1] o.s.s.w.a.i.FilterSecurityInterceptor    : RunAsManager did not change Authentication object
2022-03-21 03:47:38.105 DEBUG 7 --- [nio-8084-exec-1] o.s.security.web.FilterChainProxy        : /favicon.ico reached end of additional filter chain; proceeding with original chain
2022-03-21 03:47:38.105 DEBUG 7 --- [nio-8084-exec-1] o.s.web.servlet.DispatcherServlet        : GET "/favicon.ico", parameters={}
2022-03-21 03:47:38.107 DEBUG 7 --- [nio-8084-exec-1] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped to ResourceHttpRequestHandler ["classpath:/META-INF/resources/", "classpath:/resources/", "classpath:/static/", "classpath:/public/", "/"]
2022-03-21 03:47:38.108 DEBUG 7 --- [nio-8084-exec-1] o.s.w.s.r.ResourceHttpRequestHandler     : Resource not found
2022-03-21 03:47:38.108 DEBUG 7 --- [nio-8084-exec-1] w.c.HttpSessionSecurityContextRepository : SecurityContext is empty or contents are anonymous - context will not be stored in HttpSession.
2022-03-21 03:47:38.109 DEBUG 7 --- [nio-8084-exec-1] o.s.web.servlet.DispatcherServlet        : Completed 404 NOT_FOUND
2022-03-21 03:47:38.109 DEBUG 7 --- [nio-8084-exec-1] o.s.s.w.a.ExceptionTranslationFilter     : Chain processed normally
2022-03-21 03:47:38.109 DEBUG 7 --- [nio-8084-exec-1] s.s.w.c.SecurityContextPersistenceFilter : SecurityContextHolder now cleared, as request processing completed
2022-03-21 03:47:38.109 DEBUG 7 --- [nio-8084-exec-1] o.s.s.w.u.matcher.AntPathRequestMatcher  : Checking match of request : '/error'; against '/managed/delivery-configs/schema'
2022-03-21 03:47:38.110 DEBUG 7 --- [nio-8084-exec-1] o.s.s.web.util.matcher.OrRequestMatcher  : Trying to match using Ant [pattern='/health/**']
2022-03-21 03:47:38.110 DEBUG 7 --- [nio-8084-exec-1] o.s.s.w.u.matcher.AntPathRequestMatcher  : Checking match of request : '/error'; against '/health/**'
2022-03-21 03:47:38.110 DEBUG 7 --- [nio-8084-exec-1] o.s.s.web.util.matcher.OrRequestMatcher  : No matches found
2022-03-21 03:47:38.110 DEBUG 7 --- [nio-8084-exec-1] o.s.s.w.u.matcher.AntPathRequestMatcher  : Checking match of request : '/error'; against '/spectator/metrics'
2022-03-21 03:47:38.110 DEBUG 7 --- [nio-8084-exec-1] o.s.security.web.FilterChainProxy        : /error at position 1 of 13 in additional filter chain; firing Filter: 'WebAsyncManagerIntegrationFilter'
2022-03-21 03:47:38.110 DEBUG 7 --- [nio-8084-exec-1] o.s.security.web.FilterChainProxy        : /error at position 2 of 13 in additional filter chain; firing Filter: 'SecurityContextPersistenceFilter'

### CODE REVIEW

**Comment by gopaljayanthi** [comment]
This PR  triggered this build in this execution, please merge to master only if this succeeds:  https://spin.prod.opsmx.com/#/applications/gcp-gitprtrigger/executions/details/01FYNTDDCNH0FPR69HSVWAH8FJ

**Comment by gopaljayanthi** [comment]
This PR  triggered this build in this execution, please merge to master only if this succeeds:  https://spin.prod.opsmx.com/#/applications/gcp-gitprtrigger/executions/details/01FYNTDN2TYGRP0Y65RMS2Q68P

**Comment by gopaljayanthi** [comment]
SUCCESSFUL RunTestJar RESULT: <b>Total tests run: 196, Failures: 0, Skips: 0</b> Reviewers ,  this PR did not cause the failures in  https://jenkins.opsmx.net:8181/jenkins/job/Dev-run-tests-on-gitpr-parallel/ws/emailable-report-2287.html

**Review by Pranav-b-7 — APPROVED** [review]

**Comment by opsmxuser** [comment]
RunTestJar RESULT: <b>Tests run: 0, Failures: 0, Errors: 0, Skipped: 0</b> Developers , please check that the commits to master branch did not cause the failures in  http://jenkins.opsmx.net:8181/jenkins/job/Dev-run-tests-on-staging-master/ws/emailable-report-142.html

**Comment by opsmxuser** [comment]
RunTestJar RESULT: <b>Tests run: 0, Failures: 0, Errors: 0, Skipped: 0</b> Developers , please check that the commits to master branch did not cause the failures in  http://jenkins.opsmx.net:8181/jenkins/job/Dev-run-tests-on-staging-master/ws/emailable-report-209.html

**Pull request merged**
