### PR TITLE
OP-18551: Populate token and redirect to vela

### PR DESCRIPTION
**Pull request by rahul-chekuri**
https://devopsmx.atlassian.net/browse/OP-18463

Here is a sample token:
`eyJhbGciOiJIUzI1NiJ9.eyJncm91cHMiOlsib2VzLWRzIiwib2VzLWRldiIsIm9lcy1wbSIsImFsbHVzZXJzIiwiYWRtaW4iLCJvZXMtcWEiLCJhZG1pbmlzdHJhdG9ycyIsIm9lcy1kZXZvcHMiXSwiYXJnb0lkIjoxMSwicGF0aCI6Ii8xMjM0Iiwia2V5IjoxNjY5NzkwNzQ0MDkxLCJzdWIiOiJ1c2VyMiIsImlzcyI6ImlzZCIsImlhdCI6MTY2OTc5MDc0NCwiZXhwIjoxNjY5ODI2NzQ0LCJuYmYiOjE2Njk3OTA3NDR9.3jS-h_7wBPp8ulmFkd95-d2_hzJU6mTNqwd3NgOQF_o`

### CODE REVIEW

**Comment by opsmxuser** [comment]
This PR  triggered this build in this execution, please wait for it  and child pipelines to succeed before merging:  https://isd.prod.opsmx.net/deck/#/applications/gcp-gitprtrigger/executions/details/01GK3N3B2J4458WGT8T6KNJBM5

**Comment by gopaljayanthi** [comment]
This PR successfully triggered this build https://jenkins.opsmx.net:8181/jenkins/job/Dev-gate-forargo/51/

**Comment by gopaljayanthi** [comment]
This PR successfully triggered this build https://jenkins.opsmx.net:8181/jenkins/job/Dev-gate-forargo/52/

**Review by rsh09 — APPROVED** [review]

**Comment by gopaljayanthi** [comment]
This PR successfully triggered this build https://jenkins.opsmx.net:8181/jenkins/job/Dev-gate-forargo/58/

**Pull request merged**
