### PR TITLE
Op 13183 parsing error

### PR DESCRIPTION
**Pull request by Pranav-b-7**
We prefer small, well tested pull requests.

Please refer to [Contributing to Spinnaker](https://spinnaker.io/community/contributing/).

When filling out a pull request, please consider the following:

* Follow the commit message conventions [found here](https://spinnaker.io/community/contributing/submitting/).
* Provide a descriptive summary for your changes.
* If it fixes a bug or resolves a feature request, be sure to link to that issue.
* Add inline code comments to changes that might not be obvious.
* Squash your commits as you keep adding changes.
* Add a comment to @spinnaker/reviewers for review if your issue has been outstanding for more than 3 days.

Note that we are unlikely to accept pull requests that add features without prior discussion. The best way to propose a feature is to open an issue first and discuss your ideas there before implementing them.

https://devopsmx.atlassian.net/browse/OP-13183

### CODE REVIEW

**Comment by opsmxuser** [comment]
This PR  triggered this build in this execution, please wait for it  and child pipelines to succeed before merging:  https://isd.prod.opsmx.net/deck/#/applications/gcp-gitprtrigger/executions/details/01FZFJ35T39ZGAKPKP7H3XC539

**Comment by opsmxuser** [comment]
This PR  triggered this build in this execution, please merge to master only if this succeeds:  https://isd.prod.opsmx.net/deck/#/applications/gcp-gitprtrigger/executions/details/01FZFJ3R2CR8BT88WMGQNDB3XE

**Review by ramyaravi-opsmx — APPROVED** [review]

**Comment by opsmxuser** [comment]
SUCCESSFUL RunTestJar RESULT: <b>Total tests run: 196, Failures: 1, Skips: 0</b> Reviewers ,  this PR did not cause the failures in  https://jenkins.opsmx.net:8181/jenkins/job/Dev-run-tests-on-gitpr-parallel/ws/emailable-report-2379.html

**Comment by opsmxuser** [comment]
RunTestJar RESULT: <b>Total tests run: 437, Failures: 17, Skips: 0</b> Developers , please check that the commits to master branch did not cause the failures in  http://jenkins.opsmx.net:8181/jenkins/job/Dev-run-tests-on-staging-master/ws/emailable-report-485.html

**Pull request merged**
