### PR TITLE
OP-13535: gate review visibility API fix

### PR DESCRIPTION
**Pull request by ramyaravi-opsmx**
We prefer small, well tested pull requests.

Please refer to [Contributing to Spinnaker](https://spinnaker.io/community/contributing/).

When filling out a pull request, please consider the following:

* Follow the commit message conventions [found here](https://spinnaker.io/community/contributing/submitting/).
* Provide a descriptive summary for your changes.
* If it fixes a bug or resolves a feature request, be sure to link to that issue.
* Add inline code comments to changes that might not be obvious.
* Squash your commits as you keep adding changes.
* Add a comment to @spinnaker/reviewers for review if your issue has been outstanding for more than 3 days.

Note that we are unlikely to accept pull requests that add features without prior discussion. The best way to propose a feature is to open an issue first and discuss your ideas there before implementing them.

https://devopsmx.atlassian.net/browse/OP-13535

### CODE REVIEW

**Comment by opsmxuser** [comment]
This PR  triggered this build in this execution, please wait for it  and child pipelines to succeed before merging:  https://isd.prod.opsmx.net/deck/#/applications/gcp-gitprtrigger/executions/details/01FZF89X2GT1J2V30YHNZKGFYW

**Comment by opsmxuser** [comment]
This PR  triggered this build in this execution, please merge to master only if this succeeds:  https://isd.prod.opsmx.net/deck/#/applications/gcp-gitprtrigger/executions/details/01FZF8AFD49RGVQ4R3S5RVSAG0

**Comment by opsmxuser** [comment]
FAILURE:  RunTestJar RESULT: <b>Total tests run: 196, Failures: 2, Skips: 0</b> Reviewers , do not approve,  this PR caused the failures in  https://jenkins.opsmx.net:8181/jenkins/job/Dev-run-tests-on-gitpr-parallel/ws/emailable-report-2374.html

**Comment by opsmxuser** [comment]
More tests failed in this pipeline execution than in the preceding one, check logs here https://kibana.opsmx.net/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-03-31T05:54:09.000Z',to:'2022-03-31T05:58:30.000Z'))&_a=(columns:!(kubernetes.namespace_name,kubernetes.pod_name,message,kubernetes.container_name),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'05ac0db0-9319-11ec-9449-f5dd1683b5be',key:kubernetes.namespace_name,negate:!f,params:(query:gitpr),type:phrase),query:(match:(kubernetes.namespace_name:(query:gitpr,type:phrase))))),index:'05ac0db0-9319-11ec-9449-f5dd1683b5be',interval:auto,query:(language:kuery,query:''),sort:!(!('@timestamp',desc)))

**Review by sriharshakancharla — APPROVED** [review]

**Pull request merged**
