### PR TITLE
get approval gate status rbac issue

### PR DESCRIPTION
**Pull request by Pranav-b-7**
We prefer small, well tested pull requests.

Please refer to [Contributing to Spinnaker](https://spinnaker.io/community/contributing/).

When filling out a pull request, please consider the following:

* Follow the commit message conventions [found here](https://spinnaker.io/community/contributing/submitting/).
* Provide a descriptive summary for your changes.
* If it fixes a bug or resolves a feature request, be sure to link to that issue.
* Add inline code comments to changes that might not be obvious.
* Squash your commits as you keep adding changes.
* Add a comment to @spinnaker/reviewers for review if your issue has been outstanding for more than 3 days.

Note that we are unlikely to accept pull requests that add features without prior discussion. The best way to propose a feature is to open an issue first and discuss your ideas there before implementing them.

https://devopsmx.atlassian.net/browse/OP-12950

### CODE REVIEW

**Comment by gopaljayanthi** [comment]
This PR  triggered this build in this execution, please merge to master only if this succeeds:  https://spin.prod.opsmx.com/#/applications/gcp-gitprtrigger/executions/details/01FXS8E36WGJCNWEKHNPFCBX6K

**Comment by gopaljayanthi** [comment]
This PR  triggered this build in this execution, please merge to master only if this succeeds:  https://spin.prod.opsmx.com/#/applications/gcp-gitprtrigger/executions/details/01FXS8EAMP71E2XA72QDKH4XGF

**Comment by gopaljayanthi** [comment]
SUCCESSFUL RunTestJar RESULT: <b>Total tests run: 196, Failures: 0, Skips: 0</b> Reviewers ,  this PR did not cause the failures in  https://jenkins.opsmx.net:8181/jenkins/job/Dev-run-tests-on-gitpr-parallel/ws/emailable-report-2200.html

**Review by ramyaravi-opsmx — APPROVED** [review]

**Comment by gopaljayanthi** [comment]
RunTestJar RESULT: <b>Total tests run: 443, Failures: 0, Skips: 0</b> Developers , please check that the commits to master branch did not cause the failures in  http://jenkins.opsmx.net:8181/jenkins/job/Dev-run-tests-on-staging-master/ws/emailable-report-210.html

**Comment by gopaljayanthi** [comment]
RunTestJar RESULT: <b>Total tests run: 448, Failures: 5, Skips: 0</b> Developers , please check that the commits to master branch did not cause the failures in  http://jenkins.opsmx.net:8181/jenkins/job/Dev-run-tests-on-staging-master/ws/emailable-report-225.html

**Comment by gopaljayanthi** [comment]
RunTestJar RESULT: <b>Total tests run: 443, Failures: 0, Skips: 0</b> Developers , please check that the commits to master branch did not cause the failures in  http://jenkins.opsmx.net:8181/jenkins/job/Dev-run-tests-on-staging-master/ws/emailable-report-249.html

**Comment by gopaljayanthi** [comment]
RunTestJar RESULT: <b>Total tests run: 437, Failures: 0, Skips: 0</b> Developers , please check that the commits to master branch did not cause the failures in  http://jenkins.opsmx.net:8181/jenkins/job/Dev-run-tests-on-staging-master/ws/emailable-report-278.html

**Comment by gopaljayanthi** [comment]
RunTestJar RESULT: <b>Total tests run: 437, Failures: 0, Skips: 0</b> Developers , please check that the commits to master branch did not cause the failures in  http://jenkins.opsmx.net:8181/jenkins/job/Dev-run-tests-on-staging-master/ws/emailable-report-293.html

**Comment by gopaljayanthi** [comment]
RunTestJar RESULT: <b>Total tests run: 437, Failures: 0, Skips: 0</b> Developers , please check that the commits to master branch did not cause the failures in  http://jenkins.opsmx.net:8181/jenkins/job/Dev-run-tests-on-staging-master/ws/emailable-report-322.html

**Comment by gopaljayanthi** [comment]
RunTestJar RESULT: <b>Total tests run: 437, Failures: 5, Skips: 0</b> Developers , please check that the commits to master branch did not cause the failures in  http://jenkins.opsmx.net:8181/jenkins/job/Dev-run-tests-on-staging-master/ws/emailable-report-336.html

**Comment by gopaljayanthi** [comment]
RunTestJar RESULT: <b>Total tests run: 437, Failures: 4, Skips: 0</b> Developers , please check that the commits to master branch did not cause the failures in  http://jenkins.opsmx.net:8181/jenkins/job/Dev-run-tests-on-staging-master/ws/emailable-report-346.html

**Comment by opsmxuser** [comment]
RunTestJar RESULT: <b>Tests run: 0, Failures: 0, Errors: 0, Skipped: 0</b> Developers , please check that the commits to master branch did not cause the failures in  http://jenkins.opsmx.net:8181/jenkins/job/Dev-run-tests-on-staging-master/ws/emailable-report-143.html

**Comment by opsmxuser** [comment]
RunTestJar RESULT: <b>Tests run: 0, Failures: 0, Errors: 0, Skipped: 0</b> Developers , please check that the commits to master branch did not cause the failures in  http://jenkins.opsmx.net:8181/jenkins/job/Dev-run-tests-on-staging-master/ws/emailable-report-185.html

**Pull request merged**
