### PR TITLE
changed log.zip filename to (podname)-log

### PR DESCRIPTION
**Pull request by Lalit-Vikram-Singh**
fixing https://devopsmx.atlassian.net/browse/OP-21250

### CODE REVIEW

**Comment by aman-agrawal** [comment]
Pls share required details to PR description, eg testing details, etc

**Comment by Lalit-Vikram-Singh** [comment]
Feature: is to get Splunk logs in Cisco env from gate controller as downloadable file 

How changes are verified
Tested locally with by changing name instead of .zip in end getting log as a text file which working as expected current log file name is (<podname>-log).

Post-deployment on Cisco env: I will test this by running the pipeline (using this pipe- ) and see if the log file is opening or not

**Comment by Lalit-Vikram-Singh** [comment]
> Pls share required details to PR description, eg testing details, etc

done

**Comment by aman-agrawal** [comment]
> Feature: is to get Splunk logs in Cisco env from gate controller as downloadable file
> 
> How changes are verified Tested locally with by changing name instead of .zip in end getting log as a text file which working as expected current log file name is (-log).
> 
> Post-deployment on Cisco env: I will test this by running the pipeline (using this pipe- ) and see if the log file is opening or not

1. Pls test on cisco env and share details. As you have the cisco staging env, you should test over there.
2. Merge both commits to one.
3. I feel second commit change is irrelevant. Pls look it again.

**Comment by Lalit-Vikram-Singh** [comment]
> > Feature: is to get Splunk logs in Cisco env from gate controller as downloadable file
> > How changes are verified Tested locally with by changing name instead of .zip in end getting log as a text file which working as expected current log file name is (-log).
> > Post-deployment on Cisco env: I will test this by running the pipeline (using this pipe- ) and see if the log file is opening or not
> 
> 1. Pls test on cisco env and share details. As you have the cisco staging env, you should test over there.
> 2. Merge both commits to one.
> 3. I feel second commit change is irrelevant. Pls look it again.

1> Tested on Cisco env build the image locally pushed to Cisco env and test it working fine! now log are downloading as a file and it is opening successfully 
2> Done
3> its looking clean

**Comment by aman-agrawal** [comment]
Why deleted custom-plugin.json?

**Comment by Lalit-Vikram-Singh** [comment]
> Why deleted custom-plugin.json?



> Why deleted custom-plugin.json?

this was added in the previous commit unnecessarily, it been used to build a docker image locally

**Review by aman-agrawal — COMMENTED** [review]
Lgtm

**Pull request merged**
