### PR TITLE
Fix upstream conflict

### PR DESCRIPTION
**Pull request by singh09iet**
We prefer small, well tested pull requests.

Please refer to [Contributing to Spinnaker](https://spinnaker.io/community/contributing/).

When filling out a pull request, please consider the following:

* Follow the commit message conventions [found here](https://spinnaker.io/community/contributing/submitting/).
* Provide a descriptive summary for your changes.
* If it fixes a bug or resolves a feature request, be sure to link to that issue.
* Add inline code comments to changes that might not be obvious.
* Squash your commits as you keep adding changes.
* Add a comment to @spinnaker/reviewers for review if your issue has been outstanding for more than 3 days.

Note that we are unlikely to accept pull requests that add features without prior discussion. The best way to propose a feature is to open an issue first and discuss your ideas there before implementing them.
https://devopsmx.atlassian.net/browse/OP-13600

### CODE REVIEW

**Comment by opsmxuser** [comment]
This PR is rejected because reference to JIra ticket does not exist in the comments section of this PR. Close the PR, add Jira ticket number in comments, reopen the PR to trigger a new pipe in spinnaker.Reviewers approve only after jira reference is added.

**Comment by singh09iet** [comment]
https://devopsmx.atlassian.net/browse/OP-13600

**Comment by opsmxuser** [comment]
This PR  triggered this build in this execution, please wait for it  and child pipelines to succeed before merging:  https://isd.prod.opsmx.net/deck/#/applications/gcp-gitprtrigger/executions/details/01FZG2B9NAMR9DMHW4Y7SSG4ZA

**Comment by opsmxuser** [comment]
This PR  triggered this build in this execution, please merge to master only if this succeeds:  https://isd.prod.opsmx.net/deck/#/applications/gcp-gitprtrigger/executions/details/01FZG2BJ74K8JSBMTYKP0PJY6G

**Comment by opsmxuser** [comment]
SUCCESSFUL RunTestJar RESULT: <b>Total tests run: 196, Failures: 1, Skips: 0</b> Reviewers ,  this PR did not cause the failures in  https://jenkins.opsmx.net:8181/jenkins/job/Dev-run-tests-on-gitpr-parallel/ws/emailable-report-2381.html

**Comment by singh09iet** [comment]
https://devopsmx.atlassian.net/browse/OP-13600

**Comment by opsmxuser** [comment]
This PR  triggered this build in this execution, please wait for it  and child pipelines to succeed before merging:  https://isd.prod.opsmx.net/deck/#/applications/gcp-gitprtrigger/executions/details/01FZG397PT4D9EKRC967G9FNEV

**Comment by opsmxuser** [comment]
SUCCESSFUL RunTestJar RESULT: <b>Total tests run: 196, Failures: 1, Skips: 0</b> Reviewers ,  this PR did not cause the failures in  https://jenkins.opsmx.net:8181/jenkins/job/Dev-run-tests-on-gitpr-parallel/ws/emailable-report-2383.html

**Review by rsh09 — APPROVED** [review]
Looks good

**Pull request merged**
